spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ppees?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 2002
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.csdj.pojo